name: ci
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '8'
    - name: Adjust Gradle permission
      run: chmod +x ./gradlew
    - name: Build mod
      run: ./gradlew build
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: rs-requestify
        path: build/libs

